### ISSUE TITLE
Metro.window.create stoped working on 4.3.8

### ISSUE THREAD

**Issue by ojosojo** [olton/Metro-UI-CSS#1574]
Did a version upgrade to 4.3.8 and the Metro.window.create command trows an error
```


Metro.window.create({
            cls         : "p-0",
            title       : "AGREGAR INFORMACION",
            clsCaption  : 'bg-orange',
            btnMin      : true,
            shadow      : true,
            resizable   : true,
            btnMax      : true,
            icon        : "<span class='mif-file-empty'></spam>",
            onCaptionDblClick : function(){  } ,
            btnClose    : true,
            content     : "Hello World"
        });

```

error : 

```
metro.js:33893 Uncaught TypeError: d.makeRuntime is not a function
    at Object._create (metro.js:33893)
    at Object._createExec (metro.js:5040)
    at Object._super (metro.js:5000)
    at Object.init (metro.js:33849)
    at HTMLDivElement.<anonymous> (metro.js:4875)
    at metro.js:1322
    at E.init.forEach (<anonymous>)
    at Function.E.each (metro.js:1321)
    at E.init.each (metro.js:1336)
    at E.init.t.fn.<computed> [as window] (metro.js:4874)
```

OSX Catalina Chrome 83.0.4103.116

**Comment by olton** [comment]
Thank you, I fix it in 4.3.8

**Comment by ojosojo** [comment]
thanks @olton  solved in 4.3.9
